version: "2"
services:
  web:
    container_name: web
    build: .
    ports:
      - "80:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
